version: "3"
services:
    keycloak:
        image: quay.io/keycloak/keycloak:13.0.0
        volumes:
            - ./realm-export.json:/config/import-realm.json
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_IMPORT=/config/import-realm.json
            - PROXY_ADDRESS_FORWARDING=true  #important for reverse proxy
            - JDBC_PARAMS=enabledTLSProtocols=TLSv1.2 #workaround for aurora
            - DB_VENDOR=postgres
            - DB_ADDR=db
            - DB_PORT=5432
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_PASSWORD=keycloak
        ports:
            - 8080:8080
        depends_on:
        - db

    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: keycloak
        volumes:
            - ./var/data:/var/lib/postgresql/data
    
    node:
        build:
            context: .
            dockerfile: ./gosu_node.Dockerfile
        # keycloak-connect talks to Keycloak internally, so unless we want to modify /etc/hosts (on both host and containers) we have to allow Node.js access Keycloak as localhost:
        network_mode: host
        environment:
            - LOCAL_USER_ID
        volumes:
            - ./:/app
        working_dir: /app
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        command: bash -c "npm i; npm run dev"

