version: "3"
services:
    keycloak:
        image: quay.io/keycloak/keycloak:13.0.0
        volumes:
            - ./realm-export.json:/config/import-realm.json
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_IMPORT=/config/import-realm.json
            - PROXY_ADDRESS_FORWARDING=true  #important for reverse proxy
            - JDBC_PARAMS=enabledTLSProtocols=TLSv1.2 #workaround for aurora
        ports:
            - 8080:8080
        #network_mode: host
    
    node:
        build:
            context: .
            dockerfile: ./gosu_node.Dockerfile
        #ports:
            #- 8198:8198
        network_mode: host
        environment:
            - LOCAL_USER_ID
        volumes:
            - ./:/app
        working_dir: /app
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        command: bash -c "npm i; npm run dev"

